-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 17:27:32 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xpath
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `domainList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domainList` ;

CREATE TABLE IF NOT EXISTS `domainList` (
  `domainListID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `domainName` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`domainListID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document` ;

CREATE TABLE IF NOT EXISTS `document` (
  `documentID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `documentDomainListID` INT NOT NULL COMMENT '',
  `documentURL` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`documentID`, `documentDomainListID`)  COMMENT '',
  INDEX `fk_document_domainList1_idx` (`documentDomainListID` ASC)  COMMENT '',
  CONSTRAINT `fk_document_domainList1`
    FOREIGN KEY (`documentDomainListID`)
    REFERENCES `domainList` (`domainListID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpathValuesXPath`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xpathValuesXPath` ;

CREATE TABLE IF NOT EXISTS `xpathValuesXPath` (
  `xpathValuesID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `xpathValuesXPath` VARCHAR(45) NULL COMMENT '',
  `xpathValuesIDattribute` VARCHAR(450) NULL COMMENT '',
  `xpathValuesClassAttribute` VARCHAR(450) NULL COMMENT '',
  `xpathValuesContent` VARCHAR(45) NULL COMMENT '',
  `xpathValuesdocumentID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`xpathValuesID`, `xpathValuesdocumentID`)  COMMENT '',
  INDEX `fk_xpathValues_document_idx` (`xpathValuesdocumentID` ASC)  COMMENT '',
  CONSTRAINT `fk_xpathValues_document`
    FOREIGN KEY (`xpathValuesdocumentID`)
    REFERENCES `document` (`documentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
